sudo: required

language: bash

services:
  - docker

before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"

script:
  - build () { docker build -t $1:$2 $3; docker push $1; }
  - build "arashpz/data-caching-ci" "server" "./benchmarks/data-caching/server"
  - build "arashpz/data-caching-ci" "client" "./benchmarks/data-caching/client"
